# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 13:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(1970, 1, 1)),
        ),
    ]
