# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
