# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_auto_20170406_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoryexamination',
            name='doc',
            field=models.ImageField(upload_to='AE'),
        ),
    ]
