# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_auto_20170327_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appattachment',
            name='P_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='P_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='medialvisit',
            name='P_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='medialvisit',
            name='e_time',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='medialvisit',
            name='h_time',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='medialvisit',
            name='o_time',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='warninginfo',
            name='P_id',
            field=models.CharField(max_length=10),
        ),
    ]
