# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_auto_20170407_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('D_id', models.IntegerField()),
                ('state', models.CharField(default='1', max_length=2)),
            ],
        ),
    ]
