# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_auto_20170327_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpatientserviceinfo',
            name='abtType',
            field=models.CharField(default='x-virus', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outpatientserviceinfo',
            name='useAbt',
            field=models.CharField(max_length=1),
        ),
    ]
