# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(max_length=32),
        ),
    ]
