# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_auto_20170412_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='state',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
