# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0009_auto_20170412_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='u_id',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
