# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0009_clinic_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='ess',
            name='ess1',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ess',
            name='ess2',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ess',
            name='ess3',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mbq',
            name='q1',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mbq',
            name='q2',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mbq',
            name='q3',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sgro',
            name='H1',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sgro',
            name='H2',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sgro',
            name='H3',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
