# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0010_invitation_u_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='u_id',
            new_name='uid',
        ),
    ]
