# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0011_auto_20170412_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userGroup',
            field=models.CharField(default='2', max_length=10),
        ),
    ]
