# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0012_auto_20170412_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
