# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0015_auto_20170419_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ucg',
            old_name='CDU',
            new_name='head',
        ),
    ]
