# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0016_auto_20170419_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodgasanalysis',
            name='AE_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardiogram',
            name='AE_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lungct',
            name='AE_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lungfunc',
            name='AE_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleepdetectresult',
            name='AE_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ucg',
            name='AE_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
