# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 12:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0017_auto_20170419_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgasanalysis',
            name='date',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
        migrations.AlterField(
            model_name='cardiogram',
            name='date',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
        migrations.AlterField(
            model_name='lungct',
            name='date',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
        migrations.AlterField(
            model_name='lungfunc',
            name='date',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
        migrations.AlterField(
            model_name='sleepdetectresult',
            name='date',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
        migrations.AlterField(
            model_name='ucg',
            name='date',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
    ]
