# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0018_auto_20170419_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lungfunc',
            name='FVC1',
            field=models.FloatField(default=0.0),
        ),
    ]
