# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0019_auto_20170419_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lungfunc',
            name='FVC1',
            field=models.FloatField(null=True),
        ),
    ]
