# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0022_auto_20170419_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodgasanalysis',
            old_name='PaCO3',
            new_name='PaCO2',
        ),
    ]
