# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0024_auto_20170420_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinfo',
            name='homeAddr',
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='city_h',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='county_h',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='detail_h',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='province_h',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='county',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='province',
            field=models.CharField(max_length=20),
        ),
    ]
