# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0025_auto_20170420_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackinfo',
            name='dir',
        ),
        migrations.RemoveField(
            model_name='trackinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='trackinfo',
            name='doc',
            field=models.FileField(default='', upload_to='TrackInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appattachment',
            name='AI_id',
            field=models.IntegerField(),
        ),
    ]
