# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0027_auto_20170424_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinechange',
            name='MC_id',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicinerecord',
            name='MC_id',
            field=models.CharField(max_length=32),
        ),
    ]
