# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0028_auto_20170424_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinfo',
            name='AI_id',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
