# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0029_appinfo_ai_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinfo',
            name='S_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
