# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0033_auto_20170511_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co',
            name='aoTiZhongXin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='baDaLing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='beiBuXinQu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='changPing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='daXing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='dingLing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='dongGaoCun',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='dongSi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='dongSiHuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='fangShan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='fengTaiHuaYuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='guCheng',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='guanYuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='huaiRou',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='liuLiHe',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='menTouGou',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='miYun',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='miYunShuiKu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='nanSanHuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='nongZhanGuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='pingGu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='qianMen',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='shunYi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='tianTan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='tongZhou',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='wanLiu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='wanShouXiGong',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='xiZhiMenBei',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='yanQing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='yiZhuang',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='yongDingMenNei',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='yongLeDian',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='yuFa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='yunGang',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='zhiWuYuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='aoTiZhongXin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='baDaLing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='beiBuXinQu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='changPing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='daXing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='dingLing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='dongGaoCun',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='dongSi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='dongSiHuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='fangShan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='fengTaiHuaYuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='guCheng',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='guanYuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='huaiRou',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='liuLiHe',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='menTouGou',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='miYun',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='miYunShuiKu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='nanSanHuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='nongZhanGuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='pingGu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='qianMen',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='shunYi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='tianTan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='tongZhou',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='wanLiu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='wanShouXiGong',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='xiZhiMenBei',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='yanQing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='yiZhuang',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='yongDingMenNei',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='yongLeDian',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='yuFa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='yunGang',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='no2',
            name='zhiWuYuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='aoTiZhongXin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='baDaLing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='beiBuXinQu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='changPing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='daXing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='dingLing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='dongGaoCun',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='dongSi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='dongSiHuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='fangShan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='fengTaiHuaYuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='guCheng',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='guanYuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='huaiRou',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='liuLiHe',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='menTouGou',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='miYun',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='miYunShuiKu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='nanSanHuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='nongZhanGuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='pingGu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='qianMen',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='shunYi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='tianTan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='tongZhou',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='wanLiu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='wanShouXiGong',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='xiZhiMenBei',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='yanQing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='yiZhuang',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='yongDingMenNei',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='yongLeDian',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='yuFa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='yunGang',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='o3',
            name='zhiWuYuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='aoTiZhongXin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='baDaLing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='beiBuXinQu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='changPing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='daXing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='dingLing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='dongGaoCun',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='dongSi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='dongSiHuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='fangShan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='fengTaiHuaYuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='guCheng',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='guanYuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='huaiRou',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='liuLiHe',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='menTouGou',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='miYun',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='miYunShuiKu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='nanSanHuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='nongZhanGuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='pingGu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='qianMen',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='shunYi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='tianTan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='tongZhou',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='wanLiu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='wanShouXiGong',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='xiZhiMenBei',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='yanQing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='yiZhuang',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='yongDingMenNei',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='yongLeDian',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='yuFa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='yunGang',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm10',
            name='zhiWuYuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='baDaLing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='beiBuXinQu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='changPing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='daXing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='dingLing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='dongGaoCun',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='dongSi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='dongSiHuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='fangShan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='fengTaiHuaYuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='guCheng',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='guanYuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='huaiRou',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='liuLiHe',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='menTouGou',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='miYun',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='miYunShuiKu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='nanSanHuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='nongZhanGuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='qianMen',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='shunYi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='tianTan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='tongZhou',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='wanLiu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='wanShouXiGong',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='xiZhiMenBei',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='yanQing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='yiZhuang',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='yongDingMenNei',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='yongLeDian',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='yuFa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='yunGang',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pm25',
            name='zhiWuYuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='aoTiZhongXin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='baDaLing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='beiBuXinQu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='changPing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='daXing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='dingLing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='dongGaoCun',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='dongSi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='dongSiHuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='fangShan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='fengTaiHuaYuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='guCheng',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='guanYuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='huaiRou',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='liuLiHe',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='menTouGou',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='miYun',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='miYunShuiKu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='nanSanHuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='nongZhanGuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='pingGu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='qianMen',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='shunYi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='tianTan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='tongZhou',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='wanLiu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='wanShouXiGong',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='xiZhiMenBei',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='yanQing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='yiZhuang',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='yongDingMenNei',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='yongLeDian',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='yuFa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='yunGang',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='so2',
            name='zhiWuYuan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='aoTiZhongXin',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='baDaLing',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='beiBuXinQu',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='changPing',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='daXing',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='dingLing',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='dongDingMenNei',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='dongGaoCun',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='dongSi',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='dongSiHuan',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='fangShan',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='fengTaiHuaYuan',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='guCheng',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='guanYuan',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='huaiRou',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='liuLiHe',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='menTouGou',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='miYunShuiKu',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='nanSanHuan',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='nongZhanGuan',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='pingGu',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='qianMen',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='tianTan',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='tongZhou',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='wanLiu',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='wanShouGongXi',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='xiZhiMenBei',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='yanQing',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='yiZhuang',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='yongLeDian',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='yunGang',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='zhiWuYuan',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
