# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0035_auto_20170511_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinerecord',
            name='sign',
            field=models.CharField(default='0', max_length=2),
            preserve_default=False,
        ),
    ]
