# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0036_medicinerecord_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinerecord',
            name='doc',
            field=models.ImageField(null=True, upload_to='MR'),
        ),
    ]
