# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0039_appinfo_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinfo',
            name='date_upload',
            field=models.DateField(auto_now_add=True, default='2017-05-06'),
            preserve_default=False,
        ),
    ]
