# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0041_auto_20170516_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='IDCardNum',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
    ]
