# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0045_auto_20170518_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergcallinfo',
            name='place',
            field=models.CharField(default='\u672a\u586b\u5199', max_length=150),
        ),
        migrations.AlterField(
            model_name='inhospitalinfo',
            name='place',
            field=models.CharField(default='\u672a\u586b\u5199', max_length=150),
        ),
        migrations.AlterField(
            model_name='outpatientserviceinfo',
            name='place',
            field=models.CharField(default='\u672a\u586b\u5199', max_length=150),
        ),
    ]
