# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0046_auto_20170518_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasetype',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasetype',
            name='first',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasetype',
            name='fourth',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasetype',
            name='second',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasetype',
            name='third',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='age',
            field=models.IntegerField(),
        ),
    ]
