# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0048_auto_20170523_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catandmrc',
            name='catSum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='catandmrc',
            name='mrc',
            field=models.IntegerField(default=0),
        ),
    ]
