# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0049_auto_20170523_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lungfunc',
            name='GOLD',
            field=models.IntegerField(),
        ),
    ]
