# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 13:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0051_auto_20170607_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinechange',
            name='date',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
        migrations.AlterField(
            model_name='medicinerecord',
            name='date',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
        migrations.AlterField(
            model_name='medicineregular',
            name='date',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
    ]
