# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0052_auto_20170712_1351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppAttachment',
        ),
        migrations.RemoveField(
            model_name='medicinerecord',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='medicinerecord',
            name='name',
        ),
        migrations.RemoveField(
            model_name='medicinerecord',
            name='producer',
        ),
        migrations.AlterField(
            model_name='medicinerecord',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
