# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0054_mediafile_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
