# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_auto_20170326_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationinfo',
            old_name='honeAddr',
            new_name='homeAddr',
        ),
    ]
