# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_auto_20170327_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outpatientserviceinfo',
            old_name='use_abt',
            new_name='useAbt',
        ),
    ]
