# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_auto_20170327_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_time', models.CharField(default='0', max_length=5)),
                ('e_time', models.CharField(default='0', max_length=5)),
                ('h_time', models.CharField(default='0', max_length=5)),
                ('P_id', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MedialVisit',
        ),
    ]
