# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0010_auto_20170328_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='SGRQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_id', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=5)),
                ('S_id', models.IntegerField()),
                ('H1', models.CharField(max_length=5)),
                ('H2', models.CharField(max_length=5)),
                ('H3', models.CharField(max_length=5)),
                ('H4', models.CharField(max_length=5)),
                ('H5', models.CharField(max_length=5)),
                ('H6', models.CharField(max_length=5)),
                ('H7', models.CharField(max_length=5)),
                ('H8', models.CharField(max_length=1)),
                ('H9', models.CharField(max_length=5)),
                ('H10', models.CharField(max_length=5)),
                ('H11', models.CharField(max_length=10)),
                ('H12', models.CharField(max_length=10)),
                ('H13', models.CharField(max_length=10)),
                ('H14', models.CharField(max_length=1)),
                ('H15', models.CharField(max_length=10)),
                ('H16', models.CharField(max_length=10)),
                ('H17', models.CharField(max_length=10)),
                ('H18', models.CharField(max_length=1)),
                ('actEff', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SGRO',
        ),
    ]
