# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0011_auto_20170328_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachinfo',
            name='dir',
        ),
        migrations.RemoveField(
            model_name='attachinfo',
            name='source',
        ),
        migrations.AlterField(
            model_name='accessoryexamination',
            name='type',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='attachinfo',
            name='D_id',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='attachinfo',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
