# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0013_auto_20170328_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachinfo',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trackinfo',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
