# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0014_auto_20170328_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoryexamination',
            name='P_id',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
