# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0015_accessoryexamination_p_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachinfo',
            name='D_id',
            field=models.IntegerField(),
        ),
    ]
