# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0016_auto_20170328_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='password',
            field=models.CharField(default='000000', max_length=50),
        ),
    ]
