# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0018_auto_20170329_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergcallinfo',
            name='ecDate',
            field=models.CharField(max_length=10),
        ),
    ]
