# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0019_auto_20170329_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergcallinfo',
            old_name='ysWcTreat',
            new_name='ycWcTreat',
        ),
        migrations.RenameField(
            model_name='inhospitalinfo',
            old_name='ysWcTreat',
            new_name='ycWcTreat',
        ),
    ]
