# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0020_auto_20170329_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfo',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
