# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0025_auto_20170331_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorinfo',
            name='registerDate',
        ),
    ]
