# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0026_remove_doctorinfo_registerdate'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='doctorinfo',
        #     name='mail',
        #     field=models.CharField(default='', max_length=50),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='doctorinfo',
        #     name='registerDate',
        #     field=models.DateField(auto_now_add=True, default=''),
        #     preserve_default=False,
        # ),
    ]
