# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0028_auto_20170331_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=2)),
                ('birthday', models.DateField(blank=True)),
                ('userName', models.CharField(max_length=50)),
                ('cellphone', models.CharField(max_length=11)),
                ('weChat', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=20)),
                ('hospital', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=20)),
                ('userGroup', models.CharField(max_length=10)),
                ('registerDate', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='DoctorInfo',
        ),
    ]
